server:
  port: 8080

chat:
  name: ${CHAT_APP_NAME:EDC based chat application}
  bpn: ${CHAT_APP_BPN:BPNL000000000001}
  assetUrl: ${CHAT_APP_ASSET_URL:http://localhost:9192}
  datasource:
    host: ${CHAT_DB_HOST:localhost}
    port: ${CHAT_DB_PORT:5432}
    database: ${CHAT_DB_NAME:chat_app}
    schema: ${CHAT_DB_SCHEMA:public}
    username: ${CHAT_DB_USER:root}
    password: ${CHAT_DB_PASSWORD:root}
  edc:
    authCode: ${CHAT_AUTH_CODE:password}
    assetId: ${CHAT_ASSET_ID:edc-chat-app}
    edcUrl: ${CHAT_EDC_URL:http://localhost:9192}
spring:
  application:
    name: ${chat.name}
  threads:
    virtual:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: ${chat.datasource.schema}
    show-sql: true
  datasource:
    url: jdbc:postgresql://${chat.datasource.host}:${chat.datasource.port}/${chat.datasource.database}
    username: ${chat.datasource.username:root}
    password: ${chat.datasource.password:root}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /ui/swagger-ui
    show-common-extensions: true
    csrf:
      enabled: true
#  api-docs:
#    path: /docs/api-docs

logging:
  level:
    root: INFO
