chat:
  edc:
    authCode: password
    assetId: edc-chat-app

spring:
  application:
    name: EDC based chat application
  threads:
    virtual:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.default_schema: public
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /ui/swagger-ui
    show-common-extensions: true
    csrf:
      enabled: true
#  api-docs:
#    path: /docs/api-docs

logging:
  level:
    root: INFO
